version: '3.0'

seleniumhub:
  image: selenium/hub
  ports:
    - 4545:4444

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 4577
  links:
    - seleniumhub: hub

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 4578
  links:
    - seleniumhub: hub